icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
format = " $icon $barchart "
interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 1.0
alert = 2.0
format = " $icon root: $available.eng(w:2) "


[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 1.0
alert = 2.0
format = " $icon home: $available.eng(w:2) "

[[block]]
block = "battery"
device = "BAT0"
full_threshold = 98

[[block]]
block = "battery"
device = "BAT1"
full_threshold = 98

[[block]]
block = "memory"
format = " $icon RAM $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap SWAP $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
