#!/bin/bash

compl="[
move
exec
exit
restart
reload
shmlog
debuglog
border
layout
append_layout
workspace
focus
kill
open
fullscreen
sticky
split
floating
mark
unmark
resize
rename
nop
scratchpad
swap
title_format
mode
bar"
cmd=$(echo -e "$compl" | dmenu -p "i3#")
i3-msg "$cmd"
