#!/bin/bash

id=`xinput list | grep -Eio 'touchpad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
state=`xinput list-props $id | grep 'Device Enabled' | awk '{print $4}'`

if [ "$state" = 1 ]; then
  xinput disable $id
else
  xinput enable $id
fi

pkill -RTMIN+10 i3blocks
