#!/bin/bash

voldown() {
  amixer -D pulse sget Master | grep '\[5%\]'
  if [ "$?" = 0 ]; then
    amixer -D pulse sset Master 5%-
  else
    amixer -D pulse sset Master 5%-
  fi

  #amixer -D pulse sget Master | grep '\[4%\]' ||
  #  amixer -D pulse sget Master | grep '\[3%\]' ||
  #  amixer -D pulse sget Master | grep '\[2%\]' ||
  #  amixer -D pulse sget Master | grep '\[1%\]' ||
  #  amixer -D pulse sget Master | grep '\[0%\]'
  #if [ "$?" = 0 ]; then
  #  amixer -D pulse sset Master 5%
  #fi
}

volup() {
  amixer -D pulse sget Master | grep '\[100%\]'
  if [ "$?" = 0 ]; then
    amixer -D pulse sset Master 5%+
  else
    amixer -D pulse sset Master 5%+
  fi
}

switch_out() {
  amixer -c 0 sset Headphone toggle
  amixer -c 0 sset Speaker toggle
}

mute() {
  amixer -c 0 sset Master toggle
}

while getopts "udms" arg; do
  case $arg in
    u) volup ;;
    d) voldown ;;
    m) mute ;;
    s) switch_out ;;
  esac
done
pkill -RTMIN+10 i3blocks
